### ISSUE TITLE
Hardcoded Time Limit

### ISSUE THREAD

**Issue by NickBusey** [JackAdams/meteor-undo-redo#5]
As the docs say and the code shows, the users only see transactions that are 5 minutes old or newer when they load a page.

```
tx.undoTimeLimit = 5 * 60; // Number of seconds
```

Why is this? Just to limit the number of transactions published?

The transaction library doesn't do any cleanup of the transaction table, so why not just allow infinite undo through the entire history?

**Comment by JackAdams** [comment]
Yes, it's to limit the number of transactions published.

`tx.undoTimeLimit` can be overwritten with any number you like.

**Comment by NickBusey** [comment]
Great, thanks much. These have been very useful for me.
